version: "3.1"

services:
  database:
    image: postgis/postgis:13-3.1
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vaccinate
      POSTGRES_PASSWORD: postgres
  web:
    container_name: vial
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/vaccinate
      DASHBOARD_DATABASE_URL: postgres://postgres:postgres@database:5432/vaccinate
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - migrations
      - database
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py migrate --noinput
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/vaccinate
    volumes:
      - .:/app
    depends_on:
      - database
