import pytest


@pytest.mark.django_db
def test_counties(client):
    response = client.get("/api/counties/CA")
    assert response.json() == {
        "state_name": "California",
        "state_abbreviation": "CA",
        "state_fips_code": "06",
        "counties": [
            {"county_name": "Alameda", "county_fips_code": "06001"},
            {"county_name": "Alpine", "county_fips_code": "06003"},
            {"county_name": "Amador", "county_fips_code": "06005"},
            {"county_name": "Butte", "county_fips_code": "06007"},
            {"county_name": "Calaveras", "county_fips_code": "06009"},
            {"county_name": "Colusa", "county_fips_code": "06011"},
            {"county_name": "Contra Costa", "county_fips_code": "06013"},
            {"county_name": "Del Norte", "county_fips_code": "06015"},
            {"county_name": "El Dorado", "county_fips_code": "06017"},
            {"county_name": "Fresno", "county_fips_code": "06019"},
            {"county_name": "Glenn", "county_fips_code": "06021"},
            {"county_name": "Humboldt", "county_fips_code": "06023"},
            {"county_name": "Imperial", "county_fips_code": "06025"},
            {"county_name": "Inyo", "county_fips_code": "06027"},
            {"county_name": "Kern", "county_fips_code": "06029"},
            {"county_name": "Kings", "county_fips_code": "06031"},
            {"county_name": "Lake", "county_fips_code": "06033"},
            {"county_name": "Lassen", "county_fips_code": "06035"},
            {"county_name": "Los Angeles", "county_fips_code": "06037"},
            {"county_name": "Madera", "county_fips_code": "06039"},
            {"county_name": "Marin", "county_fips_code": "06041"},
            {"county_name": "Mariposa", "county_fips_code": "06043"},
            {"county_name": "Mendocino", "county_fips_code": "06045"},
            {"county_name": "Merced", "county_fips_code": "06047"},
            {"county_name": "Modoc", "county_fips_code": "06049"},
            {"county_name": "Mono", "county_fips_code": "06051"},
            {"county_name": "Monterey", "county_fips_code": "06053"},
            {"county_name": "Napa", "county_fips_code": "06055"},
            {"county_name": "Nevada", "county_fips_code": "06057"},
            {"county_name": "Orange", "county_fips_code": "06059"},
            {"county_name": "Placer", "county_fips_code": "06061"},
            {"county_name": "Plumas", "county_fips_code": "06063"},
            {"county_name": "Riverside", "county_fips_code": "06065"},
            {"county_name": "Sacramento", "county_fips_code": "06067"},
            {"county_name": "San Benito", "county_fips_code": "06069"},
            {"county_name": "San Bernardino", "county_fips_code": "06071"},
            {"county_name": "San Diego", "county_fips_code": "06073"},
            {"county_name": "San Francisco", "county_fips_code": "06075"},
            {"county_name": "San Joaquin", "county_fips_code": "06077"},
            {"county_name": "San Luis Obispo", "county_fips_code": "06079"},
            {"county_name": "San Mateo", "county_fips_code": "06081"},
            {"county_name": "Santa Barbara", "county_fips_code": "06083"},
            {"county_name": "Santa Clara", "county_fips_code": "06085"},
            {"county_name": "Santa Cruz", "county_fips_code": "06087"},
            {"county_name": "Shasta", "county_fips_code": "06089"},
            {"county_name": "Sierra", "county_fips_code": "06091"},
            {"county_name": "Siskiyou", "county_fips_code": "06093"},
            {"county_name": "Solano", "county_fips_code": "06095"},
            {"county_name": "Sonoma", "county_fips_code": "06097"},
            {"county_name": "Stanislaus", "county_fips_code": "06099"},
            {"county_name": "Sutter", "county_fips_code": "06101"},
            {"county_name": "Tehama", "county_fips_code": "06103"},
            {"county_name": "Trinity", "county_fips_code": "06105"},
            {"county_name": "Tulare", "county_fips_code": "06107"},
            {"county_name": "Tuolumne", "county_fips_code": "06109"},
            {"county_name": "Ventura", "county_fips_code": "06111"},
            {"county_name": "Yolo", "county_fips_code": "06113"},
            {"county_name": "Yuba", "county_fips_code": "06115"},
        ],
    }
