# Generated by Django 3.1.7 on 2021-03-10 01:15

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the API key was created",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time API key was seen, accurate to within one minute",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What this API key is being used for"),
                ),
                (
                    "key",
                    models.CharField(default=api.models.random_secret, max_length=32),
                ),
            ],
        ),
        migrations.AddField(
            model_name="apilog",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.apikey",
            ),
        ),
    ]
