# Generated by Django 3.1.8 on 2021-04-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_disable_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="switch",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
