#!/bin/bash
/app/vaccinate/manage.py lintmigrations \
  7aefb8cb6c19968ba7b97fdd099ccdd224e756f1 \
  --project-root-path ./vaccinate \
  --ignore-name \
    0038_county_fips_code_string_not_integer \
    0040_increase_size_location_import_ref \
    0044_lengthen_external_id \
    0046_rename_reports_to_report \
    0049_delete_is_test_data_columns \
    0053_rename_auth0_role_name \
    0056_completed_completed_at \
    0057_callrequest_priority \
    0061_report_is_pending_review \
    0069_more_location_denormalizations \
    0072_soft_deleted_on_reports \
    0073_callrequest_priority_group \
    0083_provider_public_id_now_unique \
    0088_last_updated_is_date_not_datetime \
    0095_rename_concordance_identifier_table \
    0097_rename_concordanceidentifier_source_to_authority \
    0098_concordanceidentifier_created_at \
    0107_decimal_for_latitude_longitude \
    0120_geography_fields \
    0133_backfill_location_created_at \
    0134_alter_location_created_at
