# Generated by Django 3.1.7 on 2021-02-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_callreport_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="callreport",
            name="airtable_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
