# Generated by Django 3.1.7 on 2021-03-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_callreport_to_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmenttag",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
