# Generated by Django 3.1.7 on 2021-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_populate_appointmenttag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmenttag",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
