# Generated by Django 3.1.7 on 2021-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_appointmenttag_slug_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilitytag",
            name="previous_names",
            field=models.JSONField(
                default=list,
                help_text="Any previous names used for this tag, used for keeping import scripts working",
            ),
        ),
        migrations.AddField(
            model_name="availabilitytag",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="availabilitytag",
            name="group",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no"), ("skip", "skip")],
                max_length=10,
                null=True,
            ),
        ),
    ]
