# Generated by Django 3.1.7 on 2021-03-01 22:00

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_populate_availability_tag_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporter",
            name="email",
            field=core.fields.CharTextField(blank=True, max_length=65000, null=True),
        ),
        migrations.AddField(
            model_name="reporter",
            name="external_id",
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="reporter",
            name="name",
            field=core.fields.CharTextField(blank=True, max_length=65000, null=True),
        ),
    ]
