# Generated by Django 3.1.7 on 2021-03-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_populate_new_reporter_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporter",
            name="airtable_name",
        ),
        migrations.RemoveField(
            model_name="reporter",
            name="auth0_name",
        ),
    ]
