# Generated by Django 3.1.7 on 2021-03-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_drop_reporter_airtable_name_auth0_name_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporter",
            name="external_id",
            field=models.SlugField(unique=True),
        ),
    ]
