# Generated by Django 3.1.7 on 2021-03-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_related_name_call_reports_is_now_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishedreport",
            name="call_reports",
        ),
        migrations.AddField(
            model_name="publishedreport",
            name="reports",
            field=models.ManyToManyField(
                db_table="published_report_reports",
                related_name="published_reports",
                to="core.Report",
            ),
        ),
        migrations.AlterModelTable(
            name="report",
            table="reports",
        ),
    ]
