# Generated by Django 3.1.7 on 2021-03-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_vaccinating_50_plus"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="public_id",
            field=models.SlugField(
                help_text="ID that we expose outside of the application", null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="public_id",
            field=models.SlugField(
                help_text="ID that we expose outside of the application", null=True
            ),
        ),
    ]
