# Generated by Django 3.1.7 on 2021-03-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_backfill_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="public_id",
            field=models.SlugField(
                help_text="ID that we expose outside of the application", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="public_id",
            field=models.SlugField(
                help_text="ID that we expose outside of the application", unique=True
            ),
        ),
    ]
