# Generated by Django 3.1.7 on 2021-03-03 04:37

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_location_report_is_test_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="contact_phone_number",
            field=core.fields.CharTextField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="public_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
