# Generated by Django 3.1.7 on 2021-03-03 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_provider_null_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="the time when the report was submitted. We will interpret this as a validity time",
            ),
        ),
    ]
