# Generated by Django 3.1.7 on 2021-03-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_location_import_json_import_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="fips_code",
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
