# Generated by Django 3.1.7 on 2021-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_insert_dc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="county",
            name="fips_code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
