# Generated by Django 3.1.7 on 2021-03-11 20:47

from django.db import migrations

# See CAVaccineInventory/help.vaccinate@5ffde0431bed035b061cc30d27a9450821ce609e


def add_availability_tags(apps, schema_editor):
    more_tags = [
        (
            "education and childcare workers",
            "education",
        ),
        ("agriculture and food workers", "agriculture"),
        ("high-risk individuals", "high_risk"),
    ]

    AvailabilityTag = apps.get_model("core", "AvailabilityTag")
    for (who, slug) in more_tags:
        AvailabilityTag.objects.create(
            name=f"Vaccinating {who}",
            slug=slug,
            group="yes",
            notes=f"This location vaccinates {who}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_availability_tag_emergency_services"),
    ]

    operations = [
        migrations.RunPython(
            add_availability_tags, reverse_code=lambda apps, schema_editor: None
        ),
    ]
