# Generated by Django 3.1.7 on 2021-03-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_add_more_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporter",
            name="external_id",
            field=models.SlugField(max_length=400, unique=True),
        ),
    ]
