# Generated by Django 3.1.7 on 2021-03-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_lengthen_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="import_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="If imported, unique identifier in the system it was imported from",
                max_length=100,
                null=True,
            ),
        ),
    ]
