# Generated by Django 3.1.7 on 2021-03-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_import_ref_charfield_not_slugfield"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="report",
            table="report",
        ),
    ]
