# Generated by Django 3.1.7 on 2021-03-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_add_more_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reporter",
            old_name="auth0_role_name",
            new_name="auth0_role_names",
        ),
    ]
