# Generated by Django 3.1.7 on 2021-04-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_reportreviewnote_reportreviewtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrequest",
            name="completed",
            field=models.BooleanField(
                default=False, help_text="Has this call been completed"
            ),
        ),
        migrations.AddField(
            model_name="callrequest",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this call was marked as completed",
                null=True,
            ),
        ),
    ]
