# Generated by Django 3.1.7 on 2021-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_completed_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrequest",
            name="priority",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Priority for call queue - higher number means higher priority",
            ),
        ),
    ]
