# Generated by Django 3.1.7 on 2021-04-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_callrequest_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callrequest",
            options={"ordering": ("-priority", "-id")},
        ),
        migrations.AddField(
            model_name="county",
            name="age_floor_without_restrictions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="county",
            name="internal_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
