# Generated by Django 3.1.7 on 2021-04-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_update_location_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="is_pending_review",
            field=models.BooleanField(
                default=False,
                help_text="Reports that are pending review by our QA team",
            ),
        ),
    ]
