# Generated by Django 3.1.7 on 2021-04-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_location_vaccinespotter_vaccinefinder_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilitytag",
            name="group",
            field=models.CharField(
                choices=[
                    ("yes", "yes"),
                    ("no", "no"),
                    ("skip", "skip"),
                    ("other", "other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
