# Generated by Django 3.1.7 on 2021-04-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_populate_denormalized_location_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="dn_latest_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.report",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="dn_latest_report_including_pending",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.report",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="dn_latest_skip_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.report",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="dn_latest_yes_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.report",
            ),
        ),
    ]
