# Generated by Django 3.1.7 on 2021-04-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_dn_fields_set_null_on_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="dn_latest_non_skip_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.report",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="dn_skip_report_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="location",
            name="dn_yes_report_count",
            field=models.IntegerField(default=0),
        ),
    ]
