# Generated by Django 3.1.8 on 2021-04-10 15:36

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_update_location_denormalizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="soft_deleted",
            field=models.BooleanField(
                default=False,
                help_text="we never delete rows from this table; all deletes are soft",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="soft_deleted_because",
            field=core.fields.CharTextField(blank=True, max_length=65000, null=True),
        ),
    ]
