# Generated by Django 3.1.8 on 2021-04-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_location_preferred_contact_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callrequest",
            options={"ordering": ("priority_group", "-priority", "-id")},
        ),
        migrations.AlterField(
            model_name="availabilitytag",
            name="previous_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Any previous names used for this tag, used for keeping import scripts working",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("research_online", "research_online"),
                    ("outbound_call", "outbound_call"),
                ],
                help_text="Preferred method of collecting status about this location",
                max_length=32,
                null=True,
            ),
        ),
    ]
