# Generated by Django 3.1.8 on 2021-04-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0076_report_originally_pending_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the QA reviewer clamed this report",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="QA reviewer who has claimed this report",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claimed_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
