# Generated by Django 3.1.8 on 2021-04-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_age_floor_without_restrictions_changed_model_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the QA reviewer claimed this report",
                null=True,
            ),
        ),
    ]
