# Generated by Django 3.1.8 on 2021-04-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_clamed_is_claimed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="full_address",
            field=models.TextField(
                blank=True,
                help_text="the entire address, including city and zip code",
                null=True,
            ),
        ),
    ]
