# Generated by Django 3.1.8 on 2021-04-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_full_address_multiline_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="airtable_id",
            field=models.CharField(
                help_text="Airtable record ID, if this has one",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="import_json",
            field=models.JSONField(
                blank=True,
                help_text="Original JSON if this record was imported from elsewhere",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="public_id",
            field=models.SlugField(
                blank=True,
                help_text="ID that we expose outside of the application",
                null=True,
            ),
        ),
    ]
