# Generated by Django 3.1.8 on 2021-04-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_populate_provider_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="public_id",
            field=models.SlugField(
                help_text="ID that we expose outside of the application", unique=True
            ),
        ),
    ]
