# Generated by Django 3.1.8 on 2021-04-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_create_initial_revisions_for_providers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="airtable_id",
            field=models.CharField(
                blank=True,
                help_text="Airtable record ID, if this has one",
                max_length=20,
                null=True,
            ),
        ),
    ]
