# Generated by Django 3.1.8 on 2021-04-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_public_id_for_provider_should_have_prefix_p"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="last_updated",
            field=models.DateField(blank=True, null=True),
        ),
    ]
