# Generated by Django 3.1.8 on 2021-04-15 20:19

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_switch_description"),
        ("core", "0088_last_updated_is_date_not_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.apikey",
                    ),
                ),
            ],
            options={
                "db_table": "import_run",
            },
        ),
        migrations.CreateModel(
            name="SourceLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_uid",
                    core.fields.CharTextField(
                        help_text="The ID within that other source, UUID etc or whatever they have - globally unique because it includes a prefix which is a copy of the source_name",
                        max_length=65000,
                        unique=True,
                    ),
                ),
                (
                    "source_name",
                    core.fields.CharTextField(
                        help_text="e.g. vaccinespotter", max_length=65000
                    ),
                ),
                (
                    "name",
                    core.fields.CharTextField(blank=True, max_length=65000, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "import_json",
                    models.JSONField(
                        blank=True,
                        help_text="Big bag of JSON with original data",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_source_locations",
                        to="core.importrun",
                    ),
                ),
            ],
            options={
                "db_table": "source_location",
            },
        ),
    ]
