# Generated by Django 3.1.8 on 2021-04-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_postgresql_extension_fuzzystrmatch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcordanceIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("identifier", models.CharField(max_length=128)),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True,
                        db_table="concordance_location",
                        related_name="concordances",
                        to="core.Location",
                    ),
                ),
                (
                    "source_locations",
                    models.ManyToManyField(
                        blank=True,
                        db_table="concordance_source_location",
                        related_name="concordances",
                        to="core.SourceLocation",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "identifier")},
            },
        ),
    ]
