# Generated by Django 3.1.8 on 2021-04-19 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_concordanceidentifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="call_request",
            field=models.ForeignKey(
                blank=True,
                help_text="the call request that this report was based on, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="core.callrequest",
            ),
        ),
    ]
