# Generated by Django 3.1.8 on 2021-04-18 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_concordanceidentifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcelocation",
            name="matched_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_source_locations",
                to="core.location",
            ),
        ),
    ]
