# Generated by Django 3.1.8 on 2021-04-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_populate_concordances_from_existing_ids"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="concordanceidentifier",
            table="concordance_identifier",
        ),
    ]
