# Generated by Django 3.1.8 on 2021-04-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_jj_pause"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concordanceidentifier",
            old_name="source",
            new_name="authority",
        ),
        migrations.AlterUniqueTogether(
            name="concordanceidentifier",
            unique_together={("authority", "identifier")},
        ),
    ]
