# Generated by Django 3.1.8 on 2021-04-21 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_rename_concordanceidentifier_source_to_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="concordanceidentifier",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
