# Generated by Django 3.1.8 on 2021-04-26 17:14

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_report_extra_columns_issue_293"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporter",
            name="display_name",
            field=core.fields.CharTextField(
                blank=True,
                help_text="If set this is displayed within VIAL in place of the Auth0 name",
                max_length=65000,
                null=True,
            ),
        ),
    ]
