# Generated by Django 3.1.8 on 2021-04-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_report_extra_columns_issue_293"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="import_run",
            field=models.ForeignKey(
                help_text="the import run that created this location, if any",
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_locations",
                to="core.importrun",
            ),
        ),
    ]
