# Generated by Django 3.1.8 on 2021-04-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_decimal_for_latitude_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availabilitytag",
            options={"ordering": ["-group", "name"]},
        ),
        migrations.AlterField(
            model_name="report",
            name="planned_closure",
            field=models.DateField(
                blank=True,
                help_text='Date this site a site plans to stop operating, "planned_closure" in our API',
                null=True,
                verbose_name="Last known event date",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_source",
            field=models.CharField(
                choices=[
                    ("ca", "Caller app"),
                    ("dc", "Data corrections"),
                    ("wb", "Web banking"),
                ],
                default="ca",
                max_length=2,
            ),
        ),
    ]
