# Generated by Django 3.2 on 2021-04-29 21:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_enable_postgis"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
