# Generated by Django 3.2 on 2021-05-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_colon_to_underscore_concordance_authorities"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="accepts_appointments",
            field=models.BooleanField(
                blank=True,
                help_text="Does this location accept appointments",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="accepts_walkins",
            field=models.BooleanField(
                blank=True, help_text="Does this location accept walkins", null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="public_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="vaccines_offered",
            field=models.JSONField(
                blank=True,
                help_text="JSON array of strings representing vaccines on offer here - enter 'null' if we do not know",
                null=True,
            ),
        ),
    ]
