# Generated by Django 3.2 on 2021-05-05 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_apikey_user"),
        ("core", "0116_location_extra_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceLocationMatchHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_location_match_history",
                        to="api.apikey",
                    ),
                ),
                (
                    "new_match_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_location_match_history",
                        to="core.location",
                    ),
                ),
                (
                    "old_match_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.location",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_location_match_history",
                        to="core.reporter",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_location_match_history",
                        to="core.sourcelocation",
                    ),
                ),
            ],
            options={
                "db_table": "source_location_match_history",
            },
        ),
    ]
