# Generated by Django 3.2.1 on 2021-05-06 22:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_sourcelocationmatchhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sourcelocationmatchhistory",
            options={"verbose_name_plural": "Source location match history"},
        ),
        migrations.AddField(
            model_name="sourcelocation",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
