# Generated by Django 3.2.2 on 2021-05-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0121_source_location_match_history_location_can_be_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrequest",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="the time the call request entered the queue.",
                null=True,
            ),
        ),
    ]
