# Generated by Django 3.2 on 2021-05-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_prep_for_unique_call_requests"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="callrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(completed=False),
                fields=("location",),
                name="unique_locations_in_queue",
            ),
        ),
    ]
