# Generated by Django 3.2.2 on 2021-05-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_alter_callrequest_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sourcelocation',
            index=models.Index(fields=['matched_location'], name='source_loca_matched_d1b866_idx'),
        ),
    ]
