# Generated by Django 3.2.3 on 2021-05-20 00:18

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0137_backfill_location_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcelocation",
            name="content_hash",
            field=core.fields.CharTextField(
                blank=True,
                help_text="Hash of the content JSON, to allow our importer clients to avoid sending data we already have",
                max_length=65000,
                null=True,
            ),
        ),
    ]
