# Generated by Django 3.2.3 on 2021-05-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_sourcelocation_content_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='internal_notes',
            new_name='private_notes',
        ),
    ]
