# Generated by Django 3.2.3 on 2021-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_sourcelocation_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Private notes'),
        ),
    ]
