# Generated by Django 3.2.3 on 2021-05-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0139_alter_report_internal_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_pending_review",
            field=models.BooleanField(
                default=False,
                help_text="Locations that are pending review by our QA team",
            ),
        ),
    ]
