# Generated by Django 3.2.3 on 2021-05-28 20:17

from django.db import migrations


def change_contact_method(apps, schema_editor):
    Location = apps.get_model("core", "Location")

    Location.objects.filter(preferred_contact_method="research_online").update(
        preferred_contact_method="online_preferred"
    )

    Location.objects.filter(preferred_contact_method="outbound_call").update(
        preferred_contact_method="call_preferred"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0140_alter_location_preferred_contact_method"),
    ]

    operations = [
        migrations.RunPython(
            change_contact_method, reverse_code=lambda apps, schema_editor: None
        )
    ]
