# Generated by Django 3.2.3 on 2021-06-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_update_preferred_contact_method"),
    ]

    sql = "ALTER TABLE location ADD COLUMN is_pending_review boolean DEFAULT False NOT NULL;"

    reverse_sql = "ALTER TABLE location DROP COLUMN is_pending_review;"

    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql=reverse_sql,
            state_operations=[
                migrations.AddField(
                    "Location",
                    "is_pending_review",
                    models.BooleanField(
                        default=False,
                        help_text="Locations that are pending review by our QA team",
                    ),
                ),
            ],
        )
    ]
