# Generated by Django 3.2.3 on 2021-06-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_update_preferred_contact_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online_only", "online_only"),
                    ("online_preferred", "online_preferred"),
                    ("call_preferred", "call_preferred"),
                    ("call_only", "call_only"),
                ],
                help_text="Preferred method of collecting status about this location",
                max_length=32,
                null=True,
            ),
        ),
    ]
