# Generated by Django 3.2.4 on 2021-06-16 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0146_remove_ct_from_source_locations_issue_655"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="appointments_walkins_last_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When accepts_walkins and accepts_appointments were last updated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="appointments_walkins_provenance_report",
            field=models.ForeignKey(
                blank=True,
                help_text="The report that last populated accepts_walkins and accepts_appointments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.report",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="appointments_walkins_provenance_source_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The source location that last populated accepts_walkins and accepts_appointments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.sourcelocation",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="vaccines_offered_last_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When vaccines_offered was last updated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="vaccines_offered_provenance_report",
            field=models.ForeignKey(
                blank=True,
                help_text="The report that last populated vaccines_offered",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.report",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="vaccines_offered_provenance_source_location",
            field=models.ForeignKey(
                blank=True,
                help_text="The source location that last populated vaccines_offered",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.sourcelocation",
            ),
        ),
    ]
