# Generated by Django 3.2.4 on 2021-06-15 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0146_remove_ct_from_source_locations_issue_655"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the QA reviewer claimed this location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="QA reviewer who has claimed this location",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claimed_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
