# Generated by Django 3.2.4 on 2021-06-22 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0151_homebound_location_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="Use the 🔍 lookup tool or enter the county number.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="core.county",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="hours",
            field=models.TextField(
                blank=True,
                help_text="Do not enter hours here for mobile clinics! File a report and put mobile clinic hours in the public notes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Enter coordinates up to 5 decimal places, or use search box and pin below to ‘pin’ the location",
                max_digits=9,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="If you're certain that this location is part of a chain or network of providers -- like CVS, Costco, or Kroger -- add the right provider network.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="core.provider",
            ),
        ),
    ]
