# Generated by Django 3.2.4 on 2021-06-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0153_add_location_review_tag_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="county",
            name="vts_priorty",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
